Algoritmo "semnome"
//
Var
   numeros: vetor [1..3, 1..3] de real
   i: inteiro


Inicio
   para i de 1 ate 3 faca
      escreva ("Digite o valor para a posição ", i, " x 1: ")
      leia (numeros[i,1])
      escreva ("Digite o valor para a posição ", i, " x 2: ")
      leia (numeros[i,2])
      escreva ("Digite o valor para a posição ", i, " x 3: ")
      leia (numeros[i,3])
   fimpara


Fimalgoritmo