Algoritmo "exemplo-3"
//
Var
   numeros: vetor [1..3, 1..3] de real
   i, j: inteiro


Inicio
   para i de 1 ate 3 faca
      para j de 1 ate 3 faca
         escreva ("Digite o valor para a posição ", i, " x ", j , ": ")
         leia (numeros[i,j])
      fimpara
   fimpara
    para i de 1 ate 3 faca
      para j de 1 ate 3 faca
         escreva (numeros[i,j])
      fimpara
      escreval()
   fimpara

Fimalgoritmo