Algoritmo "parimpar"
// Desenvolva um programa que leia um número inteiro
//e mostre se ele é PAR ou ÍMPAR.

Var
// Seção de Declarações das variáveis 
       numero: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
       escreva ("Digite um numero: ")
       leia (numero)
       
       se (numero %2 = 0 ) entao
         escreval ("É par")
       senao
         escreval ("É impar")
       fimse

Fimalgoritmo