Algoritmo "questao3"
// Escrever um algoritmo que gera e escreve os números ímpares entre 100 e 200;

var
  numero: inteiro


Inicio
    //numero := 101
    //enquanto (numero <= 200 ) faca
    //     escreval (numero)
    //     numero := numero +2
    //fimenquanto
    
    numero := 100
    enquanto (numero <=200 ) faca
         se (numero %2 <> 0 ) entao
              escreval (numero)
         fimse
         numero := numero + 1
    fimenquanto


Fimalgoritmo