Algoritmo "perimetroRetangulo"
// 
// Desenvolva um algoritmo que calcula e mostra o perímetro
//de um retângulo a partir de sua largura e altura fornecidas pelo usuário.
Var
     altura: real
     largura: real
     perimetro: real
Inicio
     escreva ("Digite a altura do retangulo: ")
     leia (altura)
     escreva ("Digite a largura do retangulo: ")
     leia (largura)
     perimetro <- (altura + largura) * 2
     escreval (" O perimetro é: ", perimetro)

Fimalgoritmo