Algoritmo "exemplo-1"
//
Var
   valores: vetor [1..3, 1..3] de inteiro
   i, j : inteiro
Inicio
   para i de 1 ate 3 faca
      para j de 1 ate 3 faca
         escreva (" Digite a ", i ," x ", j, " posição da matriz: ")
         leia (valores[i,j])
      fimpara
   fimpara

   para i de 1 ate 3 faca
      para j de 1 ate 3 faca
         escreva (valores[i,j])
      fimpara
      escreval()
   fimpara


Fimalgoritmo